# Generated by Django 2.2.7 on 2019-12-29 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('todo', '0002_auto_20191224_0510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
            preserve_default=False,
        ),
    ]
